import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, Check, Loader2, ShieldCheck } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";
import { Brand } from "@/components/studio/studio-app";
import { api, post, studioPath, type Account } from "@/lib/api";
export const Route = createFileRoute("/signin")({ head: () => ({ meta: [{ title: "Your knowledge workspace — Traina" }] }), validateSearch: (search: Record<string, unknown>): { invite?: string } => typeof search['invite'] === "string" ? { invite: search['invite'] } : {}, component: SignIn });
function SignIn() {
  const navigate = useNavigate(), { invite } = Route.useSearch();
  const [register, setRegister] = useState(false), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [name, setName] = useState(""), [workspace, setWorkspace] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [invitedRole, setInvitedRole] = useState("");
  useEffect(() => { if (!invite) return; setBusy(true); void api<{ email: string; role: string }>("/api/auth/invitation?token=" + encodeURIComponent(invite)).then(i => { setEmail(i.email); setInvitedRole(i.role); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }, [invite]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const user = await post<Account>(invite ? "/api/auth/accept-invitation" : "/api/auth/" + (register ? "register" : "login"), { token: invite, email, password, name, workspace }); await navigate({ to: "/w/$company", params: { company: user.slug } }); } catch (e) { setError(e instanceof Error ? e.message : "Could not sign in."); } finally { setBusy(false); } }
  async function demo(learner: boolean) { setBusy(true); setError(""); try { const user = await post<Account>(learner ? "/api/auth/demo-learner" : "/api/auth/demo"); if (!learner) await post(studioPath(user.slug, "/example")); await navigate({ to: "/w/$company", params: { company: user.slug } }); } catch (e) { setError(e instanceof Error ? e.message : "Could not open the demo."); } finally { setBusy(false); } }
  return <div className="studio auth-layout"><aside className="auth-story"><Link to="/" className="text-xl font-semibold">traina / apprentice</Link><div><span className="eyebrow text-white/60!">YOUR TEAM'S EXPERIENCE</span><h1>Knowledge that stays with the team.</h1><p className="mt-7 max-w-sm text-sm leading-7 text-white/70">Capture the task, understand the decisions and help someone else apply the judgment.</p><div className="mt-10 space-y-4 text-xs text-white/80">{["Masters manage who can access the workspace", "Seniors demonstrate and confirm their reasoning", "Learners replay evidence and practice safely"].map(text => <p className="flex items-center gap-3" key={text}><Check size={16} />{text}</p>)}</div></div><p className="text-xs text-white/55 flex items-center gap-2"><ShieldCheck size={15} /> Knowledge stored in your workspace</p></aside><div className="relative bg-[var(--card)]"><div className="absolute right-6 top-6"><ThemeToggle /></div><div className="auth-form"><Link to="/" className="block mb-10"><Brand /></Link><span className="eyebrow">WELCOME TO TRAINA</span><h1>{invite ? "Join your team." : register ? "Create your workspace." : "Your knowledge awaits."}</h1><p>{invite ? `You were invited as a ${invitedRole.toLowerCase() || "teammate"}. Set your name and password.` : register ? "Become the Master of a new workspace, then invite your Seniors and Learners." : "Sign in to your workspace with the access assigned to you."}</p>{error && <div role="alert" className="error-banner">{error}</div>}
      <form onSubmit={e => void submit(e)} className="space-y-5">{(register || invite) && <label className="block">Your name<input required maxLength={80} autoComplete="name" value={name} onChange={e => setName(e.target.value)} /></label>}{register && !invite && <label className="block">Workspace name<input required maxLength={80} value={workspace} onChange={e => setWorkspace(e.target.value)} placeholder="Operations North" /></label>}<label className="block">Email address<input type="email" required readOnly={!!invite} autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" /></label><label className="block">Password<input type="password" required minLength={8} maxLength={128} autoComplete={register || invite ? "new-password" : "current-password"} value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" /></label><button className="studio-button w-full" disabled={busy || !!invite && !invitedRole}>{busy ? <Loader2 size={16} className="animate-spin" /> : <ArrowRight size={16} />}{invite ? "Accept invitation" : register ? "Create workspace as Master" : "Sign in"}</button></form>
      {!invite && <><div className="text-center text-xs mt-6"><span className="text-muted-foreground">{register ? "Already have an account?" : "Starting a new team?"}</span> <button className="text-button" disabled={busy} onClick={() => { setRegister(!register); setError(""); }}>{register ? "Sign in" : "Create a workspace"}</button></div><div className="border-t border-border mt-8 pt-7"><button className="studio-button secondary w-full" disabled={busy} onClick={() => void demo(true)}>Explore learner demo <ArrowRight size={14} /></button><button className="text-button mt-4 w-full justify-center" disabled={busy} onClick={() => void demo(false)}>Explore senior demo</button><p className="text-[10px]! text-center mb-0!">An isolated workspace with fictional training material.</p></div></>}{invite && <Link to="/signin" search={{}} className="text-button mt-5">Return to sign in</Link>}
    </div></div></div>;
}
