import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { MonitorUp, Mic, Camera, EyeOff, Scan, Play, Square, RefreshCw } from "lucide-react";
import { post, studioPath, timestamp, type StudioSession } from "@/lib/api";
import { LiveCapture, type CaptureState } from "@/lib/live-capture";
import { clampPoint, normalizeMask, type Mask } from "@/lib/capture-privacy";
export type CaptureHandle = { say: (blob: Blob) => Promise<void>; seconds: () => number; recording: () => boolean; canLeave: () => boolean };
export const CapturePanel = forwardRef<CaptureHandle, { slug: string; session: StudioSession; onError: (e: unknown) => void; onRecording: (recording: boolean) => void }>(function CapturePanel({ slug, session, onError, onRecording }, ref) {
  const [state, setState] = useState<CaptureState>({ recording: false, offRecord: false, activeSeconds: session.activeSeconds || 0, mediaSeconds: session.mediaSeconds || session.activeSeconds || 0, uploads: 0, speaking: false, speech: "", connection: "Transcription not connected", camera: "Not connected", microphone: "Not connected" });
  const [selected, setSelected] = useState(false), [sandbox, setSandbox] = useState(false), [busy, setBusy] = useState(false), [captureError, setCaptureError] = useState(""), [masking, setMasking] = useState<"screen" | "camera" | null>(null), [masks, setMasks] = useState<Mask[]>([]), [cameraMasks, setCameraMasks] = useState<Mask[]>([]), [drag, setDrag] = useState<Mask | null>(null);
  const runtime = useRef<LiveCapture | null>(null), preview = useRef<HTMLCanvasElement | null>(null), cameraPreview = useRef<HTMLCanvasElement | null>(null), origin = useRef<{ x: number; y: number } | null>(null), latestError = useRef(onError), latestRecording = useRef(onRecording);
  latestError.current = onError; latestRecording.current = onRecording;
  useEffect(() => { const c = new LiveCapture(slug, session, state => { setState(state); latestRecording.current(state.recording); }, e => latestError.current(e), () => latestError.current(new Error("The one-hour capture limit was reached. Finish uploading and start the debrief."))); runtime.current = c; c.preview = preview.current || undefined; c.cameraPreview = cameraPreview.current || undefined; return () => { void c.dispose(); runtime.current = null; }; }, [slug, session.id]);
  if (runtime.current) { runtime.current.session = session; runtime.current.masks = masks; runtime.current.cameraMasks = cameraMasks; runtime.current.preview = preview.current || undefined; runtime.current.cameraPreview = cameraPreview.current || undefined; }
  useImperativeHandle(ref, () => ({ say: async blob => { if (runtime.current) await runtime.current.say(blob); }, seconds: () => Math.floor(session.phase === "capture" ? runtime.current?.state.activeSeconds || session.activeSeconds || 0 : runtime.current?.state.mediaSeconds || session.mediaSeconds || session.activeSeconds || 0), recording: () => runtime.current?.state.recording || false, canLeave: () => runtime.current?.canLeave() ?? true }));
  async function run(fn: () => Promise<unknown>) { setBusy(true); setCaptureError(""); try { await fn(); } catch (e) { setCaptureError(e instanceof Error ? e.message : "Recording could not start. Try again."); onError(e); } finally { setBusy(false); } }
  useEffect(() => { const c = runtime.current; if (!c) return; if (session.phase === "debrief" && !c.state.recording && c.state.camera !== "Not connected") void run(() => c.begin()); if (session.phase === "review" && c.state.recording) void run(() => c.pause(true)); }, [session.phase]);
  const capture = session.phase === "capture";
  function maskHandlers(target: "screen" | "camera") {
    function point(e: React.PointerEvent) { const r = (target === "screen" ? preview : cameraPreview).current!.getBoundingClientRect(); return clampPoint((e.clientX - r.left) / r.width, (e.clientY - r.top) / r.height); }
    return { onPointerDown: (e: React.PointerEvent) => { if (masking !== target) return; origin.current = point(e); e.currentTarget.setPointerCapture(e.pointerId); }, onPointerMove: (e: React.PointerEvent) => { if (origin.current && masking === target) setDrag(normalizeMask(origin.current, point(e))); }, onPointerUp: (e: React.PointerEvent) => { if (!origin.current || masking !== target) return; const m = normalizeMask(origin.current, point(e)); if (m.width > .01 && m.height > .01) (target === "screen" ? setMasks : setCameraMasks)(old => [...old, m]); origin.current = null; setDrag(null); } };
  }
  function maskOverlay(target: "screen" | "camera") { return drag && masking === target && <div className="privacy-drag" style={{ left: `${drag.x * 100}%`, top: `${drag.y * 100}%`, width: `${drag.width * 100}%`, height: `${drag.height * 100}%` }} />; }
  return <section className="studio-card overflow-hidden">
    <div className="panel-heading"><div><span className="eyebrow">LIVE EVIDENCE / MAXIMUM 60 MINUTES</span><h2>{capture ? "Senior screen, camera and microphone" : "Camera and microphone / debrief"}</h2></div><span className={`status-pill ${state.recording ? "status-green" : "status-amber"}`}>{state.recording ? "Recording" : state.offRecord ? "Off record" : "Local preview"}</span></div>
    <div className="capture-content">
      <div className="live-metrics"><span><strong>{timestamp(state.activeSeconds)}</strong> / 60:00 active</span><span>{session.pipeline?.received || 0} screenshots received</span><span>{session.pipeline?.pending || 0} awaiting Claude</span><span>{state.uploads} uploads buffered</span></div>
      {!state.recording && capture && <p className="privacy-banner"><EyeOff size={16} /> Preview stays local until you start. Draw screen and camera masks before recording; they cover snapshots and video.</p>}
      {capture && <div className={`live-preview ${masking === "screen" ? "is-masking" : ""}`} {...maskHandlers("screen")}>
        <canvas ref={preview} aria-label="Masked screen preview" />
        {!selected && <div className="preview-placeholder"><MonitorUp size={34} /><p>Select the application you will demonstrate.</p></div>}
        {maskOverlay("screen")}
      </div>}
      <div className="camera-preview-section mt-4"><div className="microphone-status"><Camera size={15} /><strong>Camera / {state.camera}</strong><span>Mic / {state.microphone}</span></div><div className={`live-preview camera-preview ${masking === "camera" ? "is-masking" : ""}`} {...maskHandlers("camera")}><canvas ref={cameraPreview} aria-label="Masked camera preview" />{state.camera === "Not connected" && <div className="preview-placeholder"><Camera size={28} /><p>Connect your camera and microphone.</p></div>}{maskOverlay("camera")}</div></div>
      <div className="flex flex-wrap gap-3 mt-4">
        {capture && <><button className="studio-button secondary small" disabled={busy || state.recording} onClick={() => void run(async () => { await runtime.current!.selectScreen(); setSelected(true); setSandbox(false); })}><MonitorUp size={15} /> Share screen</button><button className="studio-button secondary small" disabled={busy || state.recording} onClick={() => void run(async () => { await runtime.current!.sandbox(); setSelected(true); setSandbox(true); })}>Fictional sandbox</button><button className="studio-button secondary small" disabled={!selected || state.recording || busy || masking === "camera"} onClick={() => setMasking(masking ? null : "screen")}><Scan size={15} /> {masking === "screen" ? "Finish masking" : "Add privacy masks"}</button>{masks.length > 0 && <button className="text-button" disabled={state.recording} onClick={() => setMasks([])}>Clear {masks.length} screen masks</button>}</>}
        {(capture || session.phase === "debrief") && <><button className="studio-button secondary small" disabled={busy || state.recording || state.offRecord} onClick={() => void run(() => runtime.current!.connectDevices())}><Camera size={15} /> Connect camera & microphone</button><button className="studio-button secondary small" disabled={busy || state.recording || state.camera === "Not connected" || masking === "screen"} onClick={() => setMasking(masking ? null : "camera")}><Scan size={15} />{masking === "camera" ? "Finish camera masking" : "Add camera masks"}</button>{cameraMasks.length > 0 && <button className="text-button" disabled={state.recording} onClick={() => setCameraMasks([])}>Clear {cameraMasks.length} camera masks</button>}</>}
        {sandbox && capture && <select aria-label="Sandbox cost center" disabled={!selected} onChange={e => { runtime.current!.sandboxDecision = e.target.value; }}><option>4711 / Opex</option><option>0400 / Capex</option><option>Hold / Request asset number</option></select>}
      </div>
      <div className="flex flex-wrap gap-3 mt-5">
        {(capture || session.phase === "debrief") && <><button className="studio-button" disabled={!selected && capture || busy || !!masking || state.uploads > 0 && !state.recording} onClick={() => void run(() => state.recording ? runtime.current!.pause(true) : runtime.current!.begin())}>{state.recording ? <EyeOff size={16} /> : <Play size={16} />}{state.recording ? "Go off record" : capture ? "Start / resume recording" : "Resume debrief camera & microphone"}</button><button className="studio-button secondary" disabled={busy || !state.uploads} onClick={() => void run(() => runtime.current!.retryUploads())}><RefreshCw size={15} /> Retry uploads</button></>}
        {capture && <button className="studio-button secondary" disabled={busy || !session.pipeline?.received} onClick={() => void run(() => runtime.current!.finish())}><Square size={15} /> Finish activity & debrief</button>}
      </div>
      <div className="microphone-status"><Mic size={15} /><span>{state.connection}</span>{state.recording && <span className={`status-pill ${state.speaking ? "status-green" : ""}`}>{state.speaking ? "Speaking" : "Natural pause"}</span>}</div>
      {(!!session.openRecordings?.length || session.pipeline?.missingSequence !== undefined) && !state.recording && !state.uploads && <div className="privacy-banner mt-4"><p>An interrupted upload left recording fragments or screenshot sequences missing. Recover received fragments; missing audio or video will stay marked as incomplete.</p><button className="text-button" disabled={busy} onClick={() => void run(() => post(studioPath(slug, `/sessions/${session.id}/recordings/recover`)))}>Recover received recording</button></div>}
      {!selected && capture && !busy && <p className="caption">Share your screen or choose the fictional sandbox to enable Start.</p>}
      {busy && <p role="status" className="caption">{state.startup || "Completing microphone and recording uploads…"}</p>}
      {captureError && <p role="alert" className="error-banner mt-3">{captureError}</p>}
      <p className="caption mt-3">Camera and microphone stay active during recording and debrief, including while Claude speaks. Scribe transcribes the microphone; Claude uses snapshots and transcribed answers to decide what to ask; the ElevenLabs Agent voices Claude's responses. Each spoken response has an agent conversation receipt in the interview. Off record pauses both devices and all new capture. Audio and video are stored in their original language; saved text is English.</p>
      <div className="question-windows">{session.questionWindows?.map(w => <span key={w.index} className={`status-pill ${w.status === "complete" ? "status-green" : w.status === "incomplete" ? "status-amber" : ""}`}>{w.index * 10}–{(w.index + 1) * 10} min: {w.delivered}/3–5</span>)}</div>
    </div>
  </section>;
});
