import { useEffect, useRef, useState } from "react";
import { Check, Download, Play, ShieldCheck } from "lucide-react";
import { download, timestamp, type Recording, type StudioSession, type WorkMap } from "@/lib/api";
export type StudioAction = (suffix: string, body?: unknown) => Promise<void>;
function RecordingPlayer({ recordings, target }: { recordings: Recording[]; target?: { seconds: number; nonce: number } | undefined }) {
  const videos = recordings.filter(r => r.kind === "video-final"), audios = recordings.filter(r => r.kind === "audio-final");
  const [mode, setMode] = useState<"video" | "audio">(videos.length ? "video" : "audio"), [index, setIndex] = useState(0);
  const video = useRef<HTMLVideoElement | null>(null), audio = useRef<HTMLAudioElement | null>(null), seek = useRef<number | null>(null), auto = useRef(false);
  const files = mode === "video" ? videos : audios, current = files[index];
  useEffect(() => { if (!target) return; let list = videos, type: "video" | "audio" = "video"; if (!list.some(r => target.seconds >= r.startSeconds && target.seconds < r.endSeconds)) { list = audios; type = "audio"; } const i = list.findIndex(r => target.seconds >= r.startSeconds && target.seconds < r.endSeconds); if (i < 0) return; setMode(type); setIndex(i); seek.current = Math.max(0, target.seconds - list[i]!.startSeconds); auto.current = true; const player = type === "video" ? video.current : audio.current; if (type === mode && i === index && player) { player.currentTime = seek.current; seek.current = null; void player.play().catch(() => {}); } }, [target?.nonce]);
  function loaded() { const p = mode === "video" ? video.current : audio.current; if (!p) return; if (seek.current !== null) { p.currentTime = seek.current; seek.current = null; } if (auto.current) void p.play().catch(() => {}); }
  function ended() { if (index + 1 < files.length) { auto.current = true; setIndex(index + 1); } else if (mode === "video") { const next = audios.findIndex(r => r.startSeconds >= (current?.endSeconds || 0) - .1); if (next >= 0) { auto.current = true; setMode("audio"); setIndex(next); } } }
  if (!recordings.length) return <div className="privacy-banner">This older or fictional activity has screenshots and text only; no audio or video was recorded.</div>;
  return <section className="recording-player"><div className="flex justify-between gap-3 mb-3"><h2>Original activity recording</h2><div className="flex gap-2">{videos.length > 0 && <button className="text-button" onClick={() => { setMode("video"); setIndex(0); }}>Screen + voice</button>}<button className="text-button" onClick={() => { setMode("audio"); setIndex(0); }}>Audio</button></div></div>{current ? mode === "video" ? <video key={current.id} ref={video} controls preload="metadata" src={current.url} onLoadedMetadata={loaded} onEnded={ended} /> : <audio key={current.id} ref={audio} controls preload="metadata" src={current.url} onLoadedMetadata={loaded} onEnded={ended} /> : <p>No recording segment is available.</p>}<div className="flex flex-wrap gap-3 mt-3"><button className="studio-button small secondary" onClick={() => { setIndex(0); auto.current = true; const p = mode === "video" ? video.current : audio.current; if (index === 0 && p) { p.currentTime = 0; void p.play().catch(() => {}); } }}><Play size={13} /> Play full activity</button>{files.map((r, i) => <button key={r.id} className="text-button" onClick={() => { setIndex(i); auto.current = true; }}>{timestamp(r.startSeconds)}–{timestamp(r.endSeconds)}</button>)}</div><p className="caption mt-3">Off-record periods are excluded. Removed evidence appears black and silent.</p></section>;
}
export function MapPanel({ session, busy, action, onPractice, learner = false }: { session: StudioSession; busy: boolean; action: StudioAction; onCapture: () => void; onPractice: () => void; learner?: boolean }) {
  const [draft, setDraft] = useState<WorkMap | null>(session.map ? structuredClone(session.map) : null), [confirmed, setConfirmed] = useState(false), [target, setTarget] = useState<{ seconds: number; nonce: number }>();
  useEffect(() => { setDraft(session.map ? structuredClone(session.map) : null); setConfirmed(false); }, [session.id, session.phase, session.publicationVersion]);
  const edit = session.phase === "review" && !learner, map = edit ? draft : session.map;
  const jump = (seconds: number) => { setTarget({ seconds, nonce: Date.now() }); document.getElementById("recording-evidence")?.scrollIntoView({ behavior: "smooth", block: "center" }); };
  if (!map) return <div className="studio-card empty-state"><ShieldCheck size={30} /><h3>The expert's reasoning becomes your Work Map.</h3><p>Complete the recording, three debrief answers and expert confirmation to publish reliable material.</p></div>;
  return <section id="work-map" className="studio-card p-6 md:p-8"><div className="flex justify-between gap-4 flex-wrap"><div><span className="eyebrow">{edit ? "EXPERT REVIEW / CONFIRM THE TEACH-BACK" : `CONFIRMED EVIDENCE / VERSION ${session.publicationVersion || 1}`}</span><h2>{map.title}</h2></div><button className="studio-button small secondary" onClick={() => download("work-map.json", JSON.stringify(map, null, 2))}><Download size={14} /> Export map</button></div><p className="subtitle">{map.summary}</p>
    <div id="recording-evidence" className="mt-6"><RecordingPlayer recordings={session.recordings || []} target={target} /></div>
    {map.steps.map((step, i) => { const event = session.events.find(e => e.id === step.event_id), rules = map.guardrails.filter(g => g.step_position === step.position); return <div className="reference-step" key={step.position}><table className="reference-table"><tbody>
      <tr><th scope="row">Example step</th><td>Step {i + 1} of {map.steps.length}: {step.title}</td></tr>
      <tr><th scope="row">Screen moment</th><td><button className="evidence-link" onClick={() => jump(event?.elapsedSeconds || 0)}>{event?.ts || "Unknown time"}</button>, {event?.description || event?.title}<a href={event?.screenUrl} target="_blank" rel="noreferrer" className="evidence-link ml-3">Open screenshot</a>{event?.screenUrl && <img className="evidence-thumbnail" src={event.screenUrl} alt={`Screen evidence for ${step.title}`} loading="lazy" />}</td></tr>
      <tr><th scope="row">Decision</th><td>{edit ? <textarea aria-label={`Decision for step ${step.position}`} value={step.decision} onChange={e => setDraft({ ...map, steps: map.steps.map(s => s.position === step.position ? { ...s, decision: e.target.value } : s) })} /> : step.decision}</td></tr>
      <tr><th scope="row">Reason</th><td>{edit ? <textarea aria-label={`Reason for step ${step.position}`} value={step.reason_quote} onChange={e => setDraft({ ...map, steps: map.steps.map(s => s.position === step.position ? { ...s, reason_quote: e.target.value } : s) })} /> : step.reason_quote ? <q>{step.reason_quote}</q> : "The reason is not documented."}<p className="caption mt-2">{step.expert_name || session.expert} / {step.source_kind === "written" ? "Written expert statement" : <button className="evidence-link" onClick={() => jump(step.quoteSeconds ?? event?.elapsedSeconds ?? 0)}>Expert words at {timestamp(step.quoteSeconds ?? event?.elapsedSeconds ?? 0)}</button>}{step.translated && <span> / Translated from {step.source_language || "the original language"}</span>}</p></td></tr>
      <tr><th scope="row">Guardrails</th><td>{rules.map((g, j) => <div className="reference-guardrail" key={j}>{edit ? <><textarea aria-label={`Guardrail condition ${i + 1}-${j + 1}`} value={g.condition} onChange={e => setDraft({ ...map, guardrails: map.guardrails.map(x => x === g ? { ...x, condition: e.target.value } : x) })} /><textarea aria-label={`Guardrail action ${i + 1}-${j + 1}`} value={g.correct_action} onChange={e => setDraft({ ...map, guardrails: map.guardrails.map(x => x === g ? { ...x, correct_action: e.target.value } : x) })} /><textarea aria-label={`Guardrail expert statement ${i + 1}-${j + 1}`} placeholder="Add the expert statement that supports this guardrail" value={g.expert_quote} onChange={e => setDraft({ ...map, guardrails: map.guardrails.map(x => x === g ? { ...x, expert_quote: e.target.value } : x) })} /></> : <p><strong>{g.condition}</strong> {g.correct_action}</p>}<p className="caption mt-2">{g.expert_quote && <q>{g.expert_quote}</q>} {g.expert_name || session.expert} / {g.source_kind === "written" ? "Written expert statement" : <button className="evidence-link" onClick={() => jump(g.quoteSeconds ?? step.quoteSeconds ?? 0)}>Expert evidence at {timestamp(g.quoteSeconds ?? step.quoteSeconds ?? 0)}</button>}{g.translated && " / Translated quote"}</p></div>)}</td></tr>
    </tbody></table></div>; })}
    <table className="reference-table mt-6"><tbody><tr><th scope="row">Required</th><td>The debrief asks at least three follow-up questions not answered during the task and ends with a teach-back confirmed by the expert. Each step and guardrail links to screen evidence and the expert's words.</td></tr><tr><th scope="row">Teach-back</th><td>{edit ? <textarea aria-label="Expert teach-back" rows={4} value={map.teachback} onChange={e => setDraft({ ...map, teachback: e.target.value })} /> : map.teachback}</td></tr></tbody></table>
    {map.gaps.length > 0 && <div className="privacy-banner mt-5"><div><strong>Unresolved learning gaps</strong>{map.gaps.map((g, i) => <p key={i} className="mt-2">{g}</p>)}</div></div>}
    {edit && <div className="mt-6"><label className="flex gap-3 items-start"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span>I have reviewed the decisions, reasons and guardrails. This teach-back accurately represents my process.</span></label>{session.mediaPending && <p className="caption mt-3">Waiting for debrief recording uploads and consolidation before publishing.</p>}<button className="studio-button mt-5" disabled={!confirmed || busy || session.mediaPending} onClick={() => void action("/confirm", { map })}><Check size={15} /> Confirm & publish for learners</button></div>}
    {learner && <button className="studio-button mt-6" onClick={onPractice}>Practice a new case</button>}
    {!learner && session.phase === "confirmed" && <button className="text-button mt-6" disabled={busy} onClick={() => void action("/review")}>Reopen for corrections</button>}
  </section>;
}
