import { useEffect, useState } from "react";
import { Check, GraduationCap, ShieldAlert, Sparkles } from "lucide-react";
import { timestamp, type StudioSession } from "@/lib/api";
import type { StudioAction } from "./map-panel";
export function PracticePanel({ session, action, busy, onMap }: { session: StudioSession; action: StudioAction; busy: boolean; onMap: (position?: number) => void }) {
  const [choice, setChoice] = useState(""); useEffect(() => setChoice(session.validation?.choiceId || ""), [session.id, session.practice?.id]);
  if (!session.practice) return <section className="studio-card empty-state"><GraduationCap size={34} /><span className="eyebrow">LEARN / APPLY THE JUDGMENT</span><h3>A new case, grounded in expert evidence.</h3><p>Claude checks your proposed decision before it can be saved.</p><button className="studio-button" disabled={busy} onClick={() => void action("/practice")}><Sparkles size={15} /> Generate practice case</button></section>;
  const p = session.practice, v = session.validation?.choiceId === choice ? session.validation : undefined, step = session.map?.steps.find(s => s.position === v?.step_position), event = session.events.find(e => e.id === step?.event_id);
  return <section className="studio-card p-6 md:p-8"><span className="eyebrow">NEW CASE / PRACTICE BEFORE SAVING</span><h2>{p.title}</h2><p className="subtitle">{p.scenario}</p><div className="context-grid mt-5">{p.facts.map((f, i) => <div className="fact" key={i}><small>{f.label}</small><strong>{f.value}</strong></div>)}</div><h3 className="text-sm! mt-6 mb-4">What would you do before saving?</h3>{p.choices.map(c => <label key={c.id} className={`decision-option ${choice === c.id ? "selected" : ""}`}><input type="radio" name="practice-decision" value={c.id} checked={choice === c.id} disabled={busy || session.practiceSaved} onChange={() => setChoice(c.id)} /><span>{c.label}</span></label>)}
    {v && <div className={`feedback ${v.allowed ? "allowed" : ""}`}><strong className="flex gap-2">{v.allowed ? <Check size={17} /> : <ShieldAlert size={17} />}{v.allowed ? "The decision follows the expert's guardrails." : "Stop before saving."}</strong><p>{v.feedback}</p><q>{v.expert_quote}</q><button className="text-button mt-3" onClick={() => onMap(v.step_position)}>Review the expert's evidence</button></div>}
    {session.practiceSaved ? <div className="mt-6"><h3>Learning summary / {session.lastScore}/100</h3><table className="reference-table mt-4"><tbody><tr><th scope="row">Example step</th><td>{step?.title || p.title}</td></tr><tr><th scope="row">Screen moment</th><td>{event?.ts || timestamp(0)} / {event?.description || "See the confirmed map."}</td></tr><tr><th scope="row">Decision</th><td>{p.choices.find(c => c.id === v?.choiceId)?.label}</td></tr><tr><th scope="row">Reason</th><td>{v?.expert_quote}</td></tr><tr><th scope="row">Guardrails</th><td>{session.map?.guardrails.filter(g => g.step_position === step?.position).map(g => `${g.condition} ${g.correct_action}`).join(" ")}</td></tr><tr><th scope="row">Learned</th><td>{v?.mastered}</td></tr><tr><th scope="row">Next practice</th><td>{v?.next_practice}</td></tr></tbody></table><button className="studio-button mt-5" disabled={busy} onClick={() => void action("/practice")}>Practice another case</button></div> : <div className="flex flex-wrap gap-3 mt-5"><button className="studio-button" disabled={!choice || busy} onClick={() => void action("/practice/check", { choiceId: choice })}>Validate decision</button><button className="studio-button secondary" disabled={!v?.allowed || busy} onClick={() => void action("/practice/save", { choiceId: choice })}>Save validated decision</button></div>}
  </section>;
}
