import { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Check, Copy, FileText, GraduationCap, LayoutDashboard, Loader2, LogOut, Mic, MonitorUp, Plus, RefreshCw, Send, Settings, ShieldCheck, Trash2, Users, Volume2, VolumeX } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";
import { api, ApiError, post, studioPath, timestamp, type Account, type ActivityContext, type Message, type SessionSummary, type StudioSession } from "@/lib/api";
import { CapturePanel, type CaptureHandle } from "./capture-panel";
import { MapPanel } from "./map-panel";
import { PracticePanel } from "./practice-panel";
export function Brand() { return <span className="studio-brand"><span className="brand-mark"><i /><i /><i /><i /></span>traina<span className="text-[10px] font-normal tracking-normal opacity-50">/ apprentice</span></span>; }
type Member = { id: string; name: string; email: string; role: Account["role"]; active: boolean };
type Invite = { id: string; email: string; role: string; status: string; expiresAt: string };
type Draft = { id: string; title: string; phase: string; authorAccountId?: string };
const emptyContext: ActivityContext = { title: "", objective: "", application: "", initialState: "", expectedOutcome: "", prerequisites: "", rules: "", risks: "" };
const contextLabels: Record<keyof ActivityContext, string> = { title: "Activity title", objective: "What are you trying to accomplish?", application: "Application / tool", initialState: "Starting situation and inputs", expectedOutcome: "Expected result and how to verify it", prerequisites: "Prerequisites", rules: "Known rules and limits", risks: "Risks and exceptions" };
const phases: Record<StudioSession["phase"], string> = { capture: "Recording / draft", finishing: "Finalizing uploads", debrief: "Expert debrief", review: "Awaiting confirmation", confirmed: "Published" };
const connectionLabels: Record<string, string> = { claude: "Claude", voice: "ElevenLabs TTS", scribe: "ElevenLabs Scribe", agent: "ElevenLabs Agent" };
function AgentVoiceReceipt({ message }: { message: Message }) {
  if (message.role !== "assistant" || message.voiceProvider !== "ElevenLabs Agent" || !message.voiceConversationId) return null;
  return <details className="caption mt-2"><summary className="cursor-pointer" title={`ElevenLabs Agent conversation ${message.voiceConversationId}`}>Voice / ElevenLabs Agent</summary><p className="mt-1 break-all">Conversation: <code>{message.voiceConversationId}</code></p>{message.voiceAgentId && <p className="break-all">Agent: <code>{message.voiceAgentId}</code></p>}</details>;
}
export function StudioApp({ company }: { company: string }) {
  const navigate = useNavigate();
  const [account, setAccount] = useState<Account | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [busy, setBusy] = useState(false), [view, setView] = useState("home"), [session, setSession] = useState<StudioSession | null>(null), [sessions, setSessions] = useState<SessionSummary[]>([]), [context, setContext] = useState(emptyContext), [draft, setDraft] = useState(""), [voice, setVoice] = useState(true), [streamState, setStreamState] = useState("Connected"), [search, setSearch] = useState("");
  const [members, setMembers] = useState<Member[]>([]), [invitations, setInvitations] = useState<Invite[]>([]), [drafts, setDrafts] = useState<Draft[]>([]), [email, setEmail] = useState(""), [role, setRole] = useState<"SENIOR" | "LEARNER">("SENIOR"), [inviteLink, setInviteLink] = useState(""), [connection, setConnection] = useState<Record<string, { configured: boolean; verified?: boolean; model?: string; mode?: string; error?: string }> | null>(null);
  const [captureReady, setCaptureReady] = useState(false);
  const capture = useRef<CaptureHandle | null>(null), playing = useRef(new Set<string>()), delivered = useRef(new Set<string>()), active = useRef({ session, account, view }); active.current = { session, account, view };
  const report = (e: unknown) => setError(e instanceof Error ? e.message : "The operation could not be completed.");
  async function loadList(user: Account) { if (user.role === "MASTER") { const [m, i, d] = await Promise.all([api<Member[]>(`/api/t/${user.slug}/team/members`), api<Invite[]>(`/api/t/${user.slug}/team/invitations`), api<Draft[]>(studioPath(user.slug, "/drafts"))]); setMembers(m); setInvitations(i); setDrafts(d); } else setSessions(await api<SessionSummary[]>(studioPath(user.slug, "/sessions"))); }
  useEffect(() => { let live = true; void api<Account>("/api/auth/me").then(async user => { if (!live) return; if (user.slug !== company) { await navigate({ to: "/w/$company", params: { company: user.slug } }); return; } setAccount(user); await loadList(user); }).catch(e => { if (e instanceof ApiError && e.status === 401) void navigate({ to: "/signin" }); else report(e); }).finally(() => setLoading(false)); return () => { live = false; }; }, [company]);
  useEffect(() => { if (!account) return; const timer = setInterval(() => { void api<Account>("/api/auth/me").then(user => { if (user.role !== active.current.account?.role) { setSession(null); setView("home"); setAccount(user); void loadList(user).catch(report); } }).catch(e => { if (e instanceof ApiError && e.status === 401) void navigate({ to: "/signin" }); }); }, 15000); return () => clearInterval(timer); }, [account?.id]);
  useEffect(() => { if (!account || !session) return; const id = session.id, source = new EventSource(studioPath(account.slug, `/sessions/${id}/stream`)); let disconnected = false;
    const receive = (event: MessageEvent<string>) => { if (active.current.session?.id === id) { setSession(JSON.parse(event.data) as StudioSession); setStreamState("Connected"); disconnected = false; } };
    source.addEventListener("snapshot", receive as EventListener); source.onerror = () => { disconnected = true; setStreamState("Reconnecting / saved evidence is preserved"); };
    const timer = setInterval(() => { if (disconnected) void api<StudioSession>(studioPath(account.slug, `/sessions/${id}`)).then(next => { if (active.current.session?.id === id) setSession(next); }).catch(e => { if (e instanceof ApiError && [401, 403, 404].includes(e.status)) { setSession(null); setView("home"); } report(e); }); }, 5000);
    return () => { clearInterval(timer); source.close(); };
  }, [account?.slug, session?.id]);
  async function run(fn: () => Promise<unknown>) { setError(""); setBusy(true); try { await fn(); } catch (e) { report(e); } finally { setBusy(false); } }
  function canLeave() { if (capture.current && !capture.current.canLeave()) { report(new Error("Go off record and complete or retry uploads before leaving this activity.")); return false; } return true; }
  async function select(id: string) { if (id !== session?.id && !canLeave()) return; await run(async () => { setSession(await api<StudioSession>(studioPath(company, `/sessions/${id}`))); setView("activity"); }); }
  async function action(suffix: string, body: unknown = {}) { if (!session || !account) return; await run(async () => { const next = await post<StudioSession>(studioPath(company, `/sessions/${session.id}${suffix}`), body); if (next.id) setSession(next); else setSession(await api<StudioSession>(studioPath(company, `/sessions/${session.id}`))); await loadList(account); }); }
  async function acknowledge(message: Message) { if (!session || delivered.current.has(message.id)) return; delivered.current.add(message.id); try { await post(studioPath(company, `/sessions/${session.id}/questions/${message.id}/delivered`), { activeSeconds: Math.max(message.elapsedSeconds || 0, capture.current?.seconds() || session.activeSeconds || 0) }); } catch (e) { delivered.current.delete(message.id); report(e); } }
  async function say(message: Message, question = false) { if (!session || playing.current.has(message.id)) return; playing.current.add(message.id); const id = session.id;
    try { const response = await fetch(studioPath(company, "/speech"), { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId: id, messageId: message.id }) }); if (!response.ok) { const body = await response.json(); throw new Error(body.error || "ElevenLabs speech is unavailable."); } const blob = await response.blob(); if (active.current.session?.id !== id || question && !capture.current?.recording()) return; if (capture.current) await capture.current.say(blob); else { const url = URL.createObjectURL(blob), audio = new Audio(url); audio.onended = () => URL.revokeObjectURL(url); await audio.play(); } if (question && capture.current?.recording()) await acknowledge(message); }
    catch (e) { report(e); } finally { playing.current.delete(message.id); }
  }
  useEffect(() => { if (account?.role !== "SENIOR" || !session?.pendingQuestionId || !captureReady) return; const message = session.messages.find(m => m.id === session.pendingQuestionId); if (!message || delivered.current.has(message.id)) return; if (voice) void say(message, true); else if (view === "activity" && document.visibilityState === "visible") void acknowledge(message); }, [session?.pendingQuestionId, voice, view, captureReady]);
  if (!loading && !account && error) return <div className="studio min-h-screen p-10"><h1>Workspace unavailable</h1><p role="alert">{error}</p><Link to="/signin">Return to sign in</Link></div>;
  if (loading || !account) return <div className="studio min-h-screen flex justify-center items-center"><Loader2 className="animate-spin" /><span className="ml-3">Opening your workspace…</span></div>;
  const master = account.role === "MASTER", senior = account.role === "SENIOR", learner = account.role === "LEARNER";
  const pending = session?.messages.find(m => m.id === session.pendingQuestionId);
  const messages = learner ? session?.learningMessages || [] : session?.messages || [];
  return <div className="studio">
    <aside className="studio-sidebar"><Link to="/" onClick={e => { if (!canLeave()) e.preventDefault(); }}><Brand /></Link><div className="workspace-tag"><span className="avatar">{account.workspace.slice(0, 2).toUpperCase()}</span><div><strong>{account.workspace}</strong><small>{account.role.toLowerCase()} workspace</small></div></div>
      <button className={`sidebar-link ${view === "home" ? "active" : ""}`} onClick={() => { if (canLeave()) { setCaptureReady(false); setView("home"); } }}>{master ? <Users size={18} /> : learner ? <BookOpen size={18} /> : <LayoutDashboard size={18} />}{master ? "People & invitations" : learner ? "Learning library" : "My activities"}</button>
      {session && !master && <button className={`sidebar-link ${view === "activity" ? "active" : ""}`} onClick={() => setView("activity")}>{senior ? <MonitorUp size={18} /> : <GraduationCap size={18} />}{senior ? "Activity studio" : "Learn & practice"}</button>}
      {master && <button className={`sidebar-link ${view === "connections" ? "active" : ""}`} onClick={() => setView("connections")}><Settings size={18} /> Connections</button>}
      <div className="sidebar-note"><ShieldCheck size={18} /><strong>{master ? "You manage access" : senior ? "Your judgment becomes evidence" : "Learn from confirmed evidence"}</strong>{master ? "Invite a Senior to capture expertise and Learners to practice." : "Claude reasons and teaches. ElevenLabs Scribe transcribes; the ElevenLabs Agent voices Claude's words. Saved text is English."}</div>
      <div className="sidebar-account"><span className="avatar">{account.name.slice(0, 2).toUpperCase()}</span><div className="flex-1 min-w-0"><strong className="block text-xs truncate">{account.name}</strong><small className="caption">{account.role}</small></div><button aria-label="Sign out" onClick={() => { if (canLeave()) void run(async () => { await post("/api/auth/logout"); await navigate({ to: "/signin" }); }); }}><LogOut size={17} /></button></div>
    </aside>
    <main className="studio-main"><header className="studio-topbar"><span className="caption">Workspace / {master ? "Administration" : learner ? "Learning" : "Expert knowledge"}</span><div className="flex gap-3 items-center">{session && <span className="caption hidden md:inline">{streamState}</span>}<ThemeToggle /></div></header><div className="studio-page">
      {error && <div role="alert" className="error-banner flex justify-between gap-3"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError("")}>×</button></div>}
      {account.demo && <div className="privacy-banner">Fictional demo workspace / no real company data.</div>}
      {view === "home" && master && <><div className="page-heading"><span className="eyebrow">MASTER / MANAGE YOUR TEAM</span><h1>The right access for each person.</h1><p className="subtitle">Invite people by email, then share their private registration link. Your workspace has one Master.</p></div><div className="admin-grid">
        <section className="studio-card p-6"><h2>Invite a teammate</h2><form className="space-y-4 mt-5" onSubmit={e => { e.preventDefault(); void run(async () => { const invitation = await post<{ path: string }>(`/api/t/${company}/team/invitations`, { email, role }); setInviteLink(location.origin + invitation.path); setEmail(""); await loadList(account); }); }}><label>Email address<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="teammate@company.com" /></label><label>Role<select value={role} onChange={e => setRole(e.target.value as "SENIOR" | "LEARNER")}><option value="SENIOR">Senior / capture and publish</option><option value="LEARNER">Learner / learn and practice</option></select></label><button className="studio-button" disabled={busy}><Plus size={15} /> Create invitation</button></form>{inviteLink && <div className="invite-result mt-5"><p className="caption">Single-use link / expires in seven days</p><input aria-label="Invitation link" readOnly value={inviteLink} /><button className="studio-button secondary small mt-3" onClick={() => void navigator.clipboard.writeText(inviteLink).catch(report)}><Copy size={14} /> Copy registration link</button></div>}</section>
        <section className="studio-card p-6"><h2>Workspace members</h2><div className="member-list">{members.map(m => <div className="member-row" key={m.id}><div><strong>{m.name}</strong><small>{m.email}</small></div>{m.role === "MASTER" ? <span className="status-pill">Master</span> : <><select aria-label={`Role for ${m.email}`} value={m.role} disabled={busy} onChange={e => void run(async () => { await api(`/api/t/${company}/team/members/${m.id}`, { method: "PATCH", body: JSON.stringify({ role: e.target.value, active: m.active }) }); await loadList(account); })}><option value="SENIOR">Senior</option><option value="LEARNER">Learner</option></select><button className="text-button" onClick={() => void run(async () => { await api(`/api/t/${company}/team/members/${m.id}`, { method: "PATCH", body: JSON.stringify({ role: m.role, active: !m.active }) }); await loadList(account); })}>{m.active ? "Deactivate" : "Reactivate"}</button></>}</div>)}</div></section>
      </div><section className="studio-card p-6 mt-6"><h2>Invitations</h2>{!invitations.length && <p className="caption mt-3">Your invitations will appear here.</p>}{invitations.map(i => <div className="member-row" key={i.id}><div><strong>{i.email}</strong><small>{i.role} / expires {new Date(i.expiresAt).toLocaleDateString("en-US")}</small></div><span className="status-pill">{i.status}</span>{i.status === "pending" && <button className="text-button" onClick={() => void run(async () => { await api(`/api/t/${company}/team/invitations/${i.id}`, { method: "DELETE" }); await loadList(account); })}>Revoke</button>}</div>)}</section>
      {drafts.length > 0 && <section className="studio-card p-6 mt-6"><h2>Assign existing activities</h2><p className="caption mt-2">Assign preserved activities to an active Senior for review.</p>{drafts.map(d => <div className="member-row" key={d.id}><div><strong>{d.title}</strong><small>{d.phase}</small></div><select aria-label={`Senior for ${d.title}`} value={d.authorAccountId || ""} onChange={e => void run(async () => { await post(studioPath(company, `/sessions/${d.id}/assign`), { authorAccountId: e.target.value }); await loadList(account); })}><option value="" disabled>Choose Senior</option>{members.filter(m => m.role === "SENIOR" && m.active).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></div>)}</section>}</>}
      {view === "home" && !master && <><div className="page-heading"><span className="eyebrow">{senior ? "SENIOR / MAKE YOUR JUDGMENT VISIBLE" : "LEARNER / LEARN THE WHY"}</span><h1>{senior ? "Capture the thinking behind the task." : "Your team's expertise, ready to learn."}</h1><p className="subtitle">{senior ? "Set the context first. Then demonstrate the task while Claude observes, asks and keeps the evidence." : "Explore confirmed Work Maps, replay the expert's activity and practice a new case before saving a decision."}</p></div>
        {senior && <section className="studio-card p-6 mb-7"><h2>Context before the activity</h2><form onSubmit={e => { e.preventDefault(); void run(async () => { const created = await post<StudioSession>(studioPath(company, "/sessions"), context); setSession(created); setContext(emptyContext); setView("activity"); await loadList(account); }); }}><div className="context-grid mt-5">{(Object.keys(contextLabels) as (keyof ActivityContext)[]).map((key, i) => <label key={key}>{contextLabels[key]}{i < 5 && <span className="required"> *</span>}{key === "title" || key === "application" ? <input required={i < 5} maxLength={key === "title" ? 120 : 2000} value={context[key]} onChange={e => setContext({ ...context, [key]: e.target.value })} /> : <textarea required={i < 5} maxLength={2000} rows={2} value={context[key]} onChange={e => setContext({ ...context, [key]: e.target.value })} />}</label>)}</div><button className="studio-button mt-5" disabled={busy}><MonitorUp size={15} /> Create activity</button></form>{account.demo && <button className="text-button mt-4" disabled={busy} onClick={() => void run(async () => { const sample = await post<StudioSession>(studioPath(company, "/example")); setSession(sample); setView("activity"); await loadList(account); })}>Open a fictional, confirmed example <ArrowRight size={14} /></button>}</section>}
        <div className="flex justify-between items-center gap-4 mb-5"><h2>{senior ? "My activities" : "Published activities"}</h2><input className="max-w-xs" aria-label="Search activities" placeholder="Search activities" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="activity-grid">{sessions.filter(s => `${s.title} ${s.expert}`.toLowerCase().includes(search.toLowerCase())).map(s => <button className="studio-card activity-card" key={s.id} onClick={() => void select(s.id)}><div className="flex justify-between"><span className="status-pill">{phases[s.phase]}</span><ArrowRight size={16} /></div><h3 className="mt-5">{s.title}</h3><p className="caption mt-3">{s.expert}</p><small className="caption">{new Date(s.updatedAt).toLocaleDateString("en-US")}</small></button>)}</div>{!sessions.length && <div className="studio-card empty-state"><BookOpen size={32} /><h3>{senior ? "Your first activity starts here" : "Your library is waiting for a Senior"}</h3><p>{senior ? "Complete the activity context above to start." : "Confirmed activities published by your Seniors will appear here."}</p></div>}</>}
      {view === "connections" && master && <section className="studio-card p-7"><span className="eyebrow">WORKSPACE CONNECTIONS</span><h1>Claude and ElevenLabs.</h1><p className="subtitle">Claude observes, asks and teaches. Scribe transcribes the microphone. Your ElevenLabs Agent speaks each saved Claude response and records its conversation ID.</p><p className="caption mt-3">Agent conversations are created when a response is spoken with Voice on or Listen. Expand the voice receipt beneath that response to find it in the ElevenLabs dashboard.</p><button className="studio-button mt-6" disabled={busy} onClick={() => void run(async () => setConnection(await api(studioPath(company, "/status?verify=true"))))}><RefreshCw size={15} /> Verify connections</button>{connection && <div className="context-grid mt-6">{Object.entries(connection).map(([key, c]) => <div className="fact" key={key}><strong>{connectionLabels[key] || key}</strong><p>{c.verified ? "Verified" : c.configured ? "Configured / verification failed" : "Not configured"}</p>{c.mode && <p className="caption">{c.mode}</p>}{c.model && <small className="break-all">{c.model}</small>}{c.error && <p className="text-red-700 text-xs">{c.error}</p>}</div>)}</div>}</section>}
      {session && !master && view === "activity" && <div>
        <div className="page-heading flex flex-wrap justify-between gap-4"><div><span className="eyebrow">{phases[session.phase]} / {session.expert}</span><h1>{session.title}</h1></div><div className="flex gap-3 items-center"><button className="studio-button small secondary" onClick={() => setVoice(!voice)}>{voice ? <Volume2 size={15} /> : <VolumeX size={15} />}{voice ? "Voice on" : "Voice off"}</button>{senior && <button className="text-button" disabled={busy || capture.current?.recording()} onClick={() => void run(async () => { await api(studioPath(company, `/sessions/${session.id}`), { method: "DELETE" }); setSession(null); setView("home"); await loadList(account); })}><Trash2 size={14} /> Delete activity</button>}</div></div>
        {(session.analysisError || session.questionError || session.processingError) && <div className="error-banner"><p>{session.processingError || session.analysisError || session.questionError}</p>{senior && <button className="text-button mt-2" onClick={() => void action("/retry")}>Retry processing</button>}</div>}
        {session.recordingIncomplete && <p role="alert" className="privacy-banner">This recording was interrupted. Playback contains the fragments received by the server; the original activity is incomplete.</p>}
        {session.context && <details className="studio-card p-5 mb-5"><summary>Activity context / {session.context.application}</summary><div className="context-grid mt-4">{(Object.keys(contextLabels) as (keyof ActivityContext)[]).filter(k => k !== "title").map(k => <div className="fact" key={k}><small>{contextLabels[k]}</small><p>{session.context?.[k] || "Not specified"}</p></div>)}</div></details>}
        {senior && session.phase !== "confirmed" && <div className="studio-work-grid"><CapturePanel ref={capture} slug={company} session={session} onError={report} onRecording={setCaptureReady} /><section className="studio-card interview-panel"><div className="panel-heading"><div><span className="eyebrow">CLAUDE / EXPERT INTERVIEW</span><h2>{session.phase === "debrief" ? `Debrief / ${session.debriefAnswers} of 3 answered` : session.phase === "finishing" ? "Finalizing recorded evidence" : "Questions at the right moment"}</h2></div><Mic size={18} /></div>
          <div className="live-chat">{messages.slice(-25).map(m => <div className={`chat-message ${m.role}`} key={m.id}><small>{m.role === "assistant" ? "Claude" : session.expert} / {timestamp(m.elapsedSeconds || 0)}{m.translated ? " / translated" : ""}</small><p>{m.text}</p>{m.status === "deferred" && <small>Saved for the debrief</small>}{m.role === "assistant" && <button className="text-button" aria-label="Play Claude response" onClick={() => void say(m, m.id === session.pendingQuestionId)}><Volume2 size={13} /> Listen</button>}<AgentVoiceReceipt message={m} /></div>)}</div>
          {pending && <div className="question-actions"><button className="text-button" onClick={() => void acknowledge(pending)}>Mark this question as presented</button>{session.phase === "capture" && <button className="text-button" onClick={() => void action("/defer")}>Save for the end</button>}</div>}
          {session.phase !== "finishing" && <form className="chat-input" onSubmit={e => { e.preventDefault(); const text = draft; setDraft(""); void action("/turn", { text, kind: "message", language: "auto", elapsedSeconds: capture.current?.seconds() || session.activeSeconds || 0 }); }}><textarea aria-label="Answer Claude" placeholder="Answer by microphone or type a clarification…" value={draft} onChange={e => setDraft(e.target.value)} disabled={busy} /><button className="studio-button small" disabled={busy || !draft.trim()}><Send size={15} /> Send</button></form>}
          {session.phase === "finishing" && <p role="status" aria-live="polite" className="caption p-5"><Loader2 size={15} className="animate-spin inline mr-2" />{(session.pipeline?.failed || 0) > 0 ? `${session.pipeline?.failed} screenshot ${session.pipeline?.failed === 1 ? "analysis needs" : "analyses need"} retry. Received evidence is saved; use Retry processing above.` : (session.pipeline?.pending || 0) > 0 ? `Claude is analyzing ${session.pipeline?.pending} of ${session.pipeline?.received || 0} received screenshots. The one-hour recording limit is a maximum, not a required duration.` : session.mediaPending || (session.openRecordings?.length || 0) > 0 ? "Screenshot analysis is complete. Waiting for received audio and video fragments to consolidate." : "Screenshot analysis is complete. Finishing the activity and preparing the expert debrief…"}</p>}
        </section></div>}
        {senior && session.events.length > 0 && <details className="studio-card p-5 my-5"><summary>Screen evidence / {session.events.length} observed moments</summary><p className="caption mt-3">Removing a moment also mutes its linked audio, obscures the associated video and withdraws published versions until a new review.</p>{session.events.map(e => <div className="member-row" key={e.id}><div><a href={e.screenUrl} target="_blank" rel="noreferrer">{e.ts} / {e.title}</a><small>{e.decision}</small></div><button className="text-button" disabled={busy || capture.current?.recording()} onClick={() => void run(async () => { setSession(await api<StudioSession>(studioPath(company, `/sessions/${session.id}/events/${e.id}`), { method: "DELETE" })); await loadList(account); })}>Remove evidence</button></div>)}</details>}
        {senior && session.doubts && session.doubts.length > 0 && <details className="studio-card p-5 my-5"><summary>Saved doubts / {session.doubts.filter(d => d.status === "open").length} open</summary>{session.doubts.map(d => <p className="caption mt-3" key={d.id}>{timestamp(d.elapsedSeconds)} / {d.text} / {d.status}</p>)}</details>}
        {(session.map || learner) && <div className="mt-6"><MapPanel session={session} busy={busy} action={action} onCapture={() => setView("activity")} onPractice={() => document.getElementById("learner-practice")?.scrollIntoView({ behavior: "smooth" })} learner={learner} /></div>}
        {learner && <><div id="learner-practice" className="mt-6"><PracticePanel session={session} busy={busy} action={action} onMap={() => document.getElementById("work-map")?.scrollIntoView({ behavior: "smooth" })} /></div><section className="studio-card p-6 mt-6"><h2>Ask about this activity</h2><p className="caption mt-2">Claude uses confirmed expert evidence. Your questions and practice stay private to your account.</p><div className="live-chat compact">{messages.map(m => <div key={m.id} className={`chat-message ${m.role}`}><small>{m.role === "assistant" ? "Claude" : "You"}</small><p>{m.text}</p>{m.role === "assistant" && <button className="text-button" onClick={() => void say(m)}><Volume2 size={13} /> Listen</button>}<AgentVoiceReceipt message={m} /></div>)}</div><form className="chat-input" onSubmit={e => { e.preventDefault(); const text = draft; setDraft(""); void action("/turn", { text }); }}><textarea aria-label="Ask the learning tutor" required value={draft} onChange={e => setDraft(e.target.value)} placeholder="What would change if…?" /><button className="studio-button" disabled={busy || !draft.trim()}><Send size={15} /> Ask Claude</button></form></section></>}
      </div>}
      {busy && <div role="status" className="processing-toast"><Loader2 className="animate-spin" size={16} /> Saving / Claude is processing…</div>}
    </div></main>
  </div>;
}
